### ISSUE TITLE
Using mailersend templates 

### ISSUE THREAD

**Issue by mozami** [mailersend/mailersend-laravel-driver#12]
Hi,

Im trying out the package with a simple Laravel mailable and referencing a template as per the documentation as follows:

`
    class UserCreated extends Mailable
    {
        use Queueable, SerializesModels, MailerSendTrait;

        public function build()
        { 
            $variables = [
                new Variable('info@myaccount.com', [
                    'name' => 'Joe'
                    'company' => 'Acme Co'
                ])
            ];
        
            return $this
                ->mailersend('ynrw7gy2pn42k8e3', $variables);
        }
    }
`

However, this expects a blade view (see error attached).
If we adding a blade view with `->view('emails.test_html')` then ends up sending the mail but ignoring the template. 
Am I doing this correctly - or does the template ID need to be passed in a different way?

![image](https://user-images.githubusercontent.com/613641/144017188-b1e1c01b-e96c-4eed-9c94-7a52554820c6.png)
![image](https://user-images.githubusercontent.com/613641/144017222-1ebc5f42-9360-4f2a-b143-d6509d620ece.png)

**Comment by jonasbrenig** [comment]
Having the same issue

**Comment by fosron** [comment]
Please look into [README.md](https://github.com/mailersend/mailersend-laravel-driver#usage) for latest example of Laravel driver usage. Thanks.

If you have any further questions, please contact [our support team](https://www.mailersend.com/contact-us).

**Comment by jonasbrenig** [comment]
@fosron Than you but can you point us in the direction of what we might be doing wrong?

It would be very helpful to have an explicit example for sending with a template.

And please check on your end if it really works for you when you are providing a template ID.


Thank you :)
