### ISSUE TITLE
Update for Laravel 9 and PHP 8

### ISSUE THREAD

**Issue by fosron** [mailersend/mailersend-laravel-driver#15]
Implement migration from Swift Mailer to Symfony Mailer for Laravel 9

https://github.com/laravel/framework/pull/38481

Release as v2 branch to not introduce BC.

**Comment by IsraelOrtuno** [comment]
I guess this is a breaking change for the current version?

https://laravel.com/docs/9.x/upgrade#symfony-mailer

**Comment by fosron** [comment]
@IsraelOrtuno Yes, we will be updating and releasing a v2 for the driver soon.

**Comment by fosron** [comment]
There's a WIP version ready - `composer require mailersend/laravel-driver:dev-v2-update-symfonymailer` , need to test a little bit more before releasing v2.
