### ISSUE TITLE
Error in MailersendTrait with new sendAt

### ISSUE THREAD

**Issue by msch-alpgis** [mailersend/mailersend-laravel-driver#17]
The new implemented `sendAt` for mailersend method of MailerSendTrait produces errors or at least PHP warnings, if no date is set. `trying to access property timestamp of null`.

https://github.com/mailersend/mailersend-laravel-driver/blob/09f4aa96d73e4283481f427c19c8d3786a76b232/src/MailerSendTrait.php#L30

Perhaps replace with:

```php
if(isset($sendAt)) {
    Arr::set($mailersendData, MailerSendTransport::MAILERSEND_DATA_SEND_AT, $sendAt->timestamp); 
}
```

**Comment by fosron** [comment]
Thanks for noticing @msch-alpgis , we are releasing a hotfix 🙏
