### ISSUE TITLE
Incompatibilities with other packages

### ISSUE THREAD

**Issue by javif89** [mailersend/mailersend-laravel-driver#2]
When trying to install this I found that it was incompatible with:

`sentry/sentry-laravel`
`mailerlite/mailerlite-api-v2-php-sdk`

Most of the issues cam from the guzzle6-adapter dependencies which requires packages such as `php-http/httplug` and `php-http/discovery`. Those underlying packages have conflicts with the versions the other packages use

**Comment by fosron** [comment]
You will need to update those packages to their latest versions for this to work. Also, from what i understand, the actual incompatibilities are related to `mailersend/php` package, and not the Laravel Driver.

**Comment by fosron** [comment]
Maybe a solution would be to remove `guzzle6-adapter` as a dependency, but i do not know how this would work further down the line.
