### ISSUE TITLE
Compatibility with alternative mailable syntax

### ISSUE THREAD

**Issue by fosron** [mailersend/mailersend-laravel-driver#21]
We need to update our examples to have both old and new syntax mentioned,

and making sure it works with both.

https://github.com/laravel/framework/pull/44462

**Comment by simuse** [comment]
Any update on that issue ?

**Comment by fosron** [comment]
Not yet, theres no big migration or an imminent deprecation of the old syntax, so we do not consider this urgent.

**Comment by fosron** [comment]
Issue escalated, will be worked on soon.
