### ISSUE TITLE
Compatibility with newer version of symfony/mime package

### ISSUE THREAD

**Issue by zeshan77** [mailersend/mailersend-laravel-driver#27]
[Symfony/mime](https://github.com/symfony/mime) has deprecated function `attachPart()` in favour of `addPart()` in one
of its [recent releases](https://github.com/symfony/mime/blob/1e8005a7cbd79fb824ad81308ef2a76592a08bc0/CHANGELOG.md#62) (6.2).

This package needs to be updated in order to make it work with the aforementioned package's update.

<img width="888" alt="Screenshot 2023-04-06 at 11 41 01 PM" src="https://user-images.githubusercontent.com/2544017/230466854-e2fe6e06-d521-49f2-bd1f-d884a951f89e.png">

**Comment by fosron** [comment]
Escalated.
