### ISSUE TITLE
cannot send email without From name

### ISSUE THREAD

**Issue by lechbaczynski** [mailersend/mailersend-laravel-driver#3]
got error:
![image](https://user-images.githubusercontent.com/1127623/102072052-9cb61480-3e01-11eb-84a1-78a321cdbd9c.png)

after using function **from** from  Illuminate/Mail/Mailable
public function from($address, $name = null)
with just one parameter like: from(email@example.com)

**Comment by alex-kuttner** [comment]
For anyone with the same error you need to include the second param like so `->from('contact@domain.com', 'Sales')`
