### ISSUE TITLE
Laravel 10 install issue, psr/http-message mismatch

### ISSUE THREAD

**Issue by cjaoude** [mailersend/mailersend-laravel-driver#30]
Laravel 10 requires `psr/http-message` 2.0. but `mailersend/laravel-driver` requires 1.0. Downgrading the laravel requirement solves this, but seems to me not a great idea. Tested on older migrated L9 to L10 app, but also on fresh Laravel 10 install, and issue persisted. Please update `mailersend/laravel-driver`. TNX!

```
mailersend/mailersend v0.8.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0
```

**Comment by fosron** [comment]
Please make sure it's not one of the sub-dependencies on your project, as the main Laravel repo does not require psr/http-message.
