### ISSUE TITLE
 Compatibility issues with Laravel 10.X.

### ISSUE THREAD

**Issue by tecbay** [mailersend/mailersend-laravel-driver#32]
My composer.json:
   "require": {
        "php": "^8.2",
        "devnoiseconsulting/laravel-scout-postgres-tsvector": "^9.1",
        "doctrine/dbal": "^3.6.1",
        "guzzlehttp/guzzle": "^7.7",
        "http-interop/http-factory-guzzle": "^1.2",
        "inertiajs/inertia-laravel": "^0.6.9",
        "laravel/framework": "^v10.5.1",
        "laravel/horizon": "^5.16",
        "laravel/pennant": "^1.2",
        "laravel/sanctum": "^v3.2.1",
        "laravel/scout": "^10.0",
        "laravel/socialite": "^5.6",
        "laravel/tinker": "^2.7",
        "laravel/vapor-cli": "^1.58",
        "laravel/vapor-core": "^2.31",
        "laravel/vapor-ui": "^1.7",
        "league/flysystem-aws-s3-v3": "^3.0",
        "meilisearch/meilisearch-php": "^1.0",
        "predis/predis": "^2.1",
        "propaganistas/laravel-phone": "^5.0",
        "pusher/pusher-php-server": "^7.2",
        "spatie/laravel-cookie-consent": "^3.2",
        "spatie/laravel-data": "^3.2",
        "spatie/laravel-event-sourcing": "^7.3",
        "spatie/laravel-medialibrary": "^10.7",
        "spatie/laravel-model-states": "^2.4",
        "spatie/laravel-settings": "^2.8.3",
        "spatie/laravel-sitemap": "^6.3",
        "spatie/laravel-typescript-transformer": "^2.1.7",
        "spatie/typescript-transformer": "^2.1",
        "stancl/tenancy": "^3.7",
        "staudenmeir/laravel-adjacency-list": "^1.0",
        "stripe/stripe-php": "^10.21",
        "tightenco/ziggy": "^1.5"
    },

Output:
-------------------

  Problem 1
    - mailersend/laravel-driver v2.2.0 requires mailersend/mailersend ^0.8.0 -> satisfiable by mailersend/mailersend[v0.8.0].
    - mailersend/laravel-driver[v0.1.0, ..., v0.1.1] require php ^7.4 -> your php version (8.2; overridden via config.platform, actual: 8.2.7) does not satisfy that requirement.
    - mailersend/laravel-driver[v1.0, ..., v1.1.1] require illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - mailersend/laravel-driver[v2.0.0, ..., v2.1.0] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
    - mailersend/mailersend v0.8.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires mailersend/laravel-driver * -> satisfiable by mailersend/laravel-driver[v0.1.0, v0.1.1, v1.0, ..., v1.1.1, v2.0.0, v2.1.0, v2.2.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require mailersend/laravel-driver:*" to figure out if any version is installable, or "composer require mailersend/laravel-driver:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by fosron** [comment]
```mailersend/mailersend v0.8.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.``` One of your packages has locked the rest out with a higher `psr/http-message` version.

**Comment by tecbay** [comment]
Thanks, @fosron.
I have deleted my composer.lock file and re-run `composer i`. 
Everything working fine. 
But i am not sure is it the right way?

**Comment by fosron** [comment]
@tecbay we will be adding support for v2 later down the road, if this works for now, thats the way to go.
