### ISSUE TITLE
PSR/HTTP-MESSAGE 2.0 work? 

### ISSUE THREAD

**Issue by rtaylor82** [mailersend/mailersend-laravel-driver#33]
Can we update composer.json to support psr/http-message 2.0 yet? 

Problem 1
    - mailersend/mailersend v0.8.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by fosron** [comment]
This has to be updated upstream.
