### ISSUE TITLE
Update to use latest SDK version

### ISSUE THREAD

**Issue by fosron** [mailersend/mailersend-laravel-driver#34]

**Comment by fosron** [comment]
Could not be updated to latest SDK version as it does not use symfony 6 as a dependency.

**Comment by rtaylor82** [comment]
So this will allow us to use the latest php sdk?  I'm looking to manage sender identities with it and that does not exist in the locked version 0.8.0.

**Comment by fosron** [comment]
That is the plan. But we have to do some other core dependencies updates and that will take a little bit of time.

**Comment by rtaylor82** [comment]
@fosron  That's awesome! Any idea timeline?  I would love to avoid having to write all the API calls... Trying to update my roadmap
