### ISSUE TITLE
Issues with email attachments

### ISSUE THREAD

**Issue by PriceNathan** [mailersend/mailersend-laravel-driver#39]
Context: Laravel 10 / PHP 8.2

We've encountered an issue in sending an email with a raw data (JSON) attachment. We use multiple mailers and this issue is only encountered using mailersend, mailgun works as intended. I'm not sure where this inconsistency comes from, and due to the fact that mailgun works where mailersend doesn't it seems as if it's an issue. 

We use a json-encoded PHP array to send a .json file to the email recipient. 

This is the code we're using currently (with identifiable information replaced):

```
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;


class MyMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;
    
    public $data;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($data)
    {
        $this->data = json_encode($data);
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        $subject = 'My Email';
        $name = 'Me';
        $from = 'my@email.com';

        return $this->from($from, $name)
                    ->subject($subject)
                    ->view('myEmailTemplate')
                    ->attachData($this->data, 'myJsonData.json', [
                        'mime' => 'application/json',]);               
    }
}
```

I have also attempted using the new laravel attachments method like this:
```
public function attachments(): array
  {
      return [
          Attachment::fromData(fn () => $jsonData, 'myJsonData.json')
              ->withMime('application/json'),
      ];
  }
```
    
 Both attempts result in this message returned by the mailersend API:
`Could not validate the attached file. Filename and attached file does not match. #MS42202`

**Comment by PriceNathan** [comment]
Edited code in post for better clarity

**Comment by fosron** [comment]
We do not support sending `json` files using our API https://developers.mailersend.com/api/v1/email.html#supported-file-types
