### ISSUE TITLE
Laravel 8 Not supported

### ISSUE THREAD

**Issue by roni-estein** [mailersend/mailersend-laravel-driver#4]
Do you need a PR to roll this out?

**Comment by fosron** [comment]
Hey, that would be really awesome! We always welcome community contributions!

**Comment by roni-estein** [comment]
Sorry in the end our office only approves this kind of stuff for OSS, also that project was released yesterday afternoon and is already live on another provider. This is a pretty easy update. You could probably also probably just buy a shift for $10-30  from https://laravelshift.com/ and be available to PHP 7.4 and 8 and laravel 7 and 8 in an hour. Seems like a good call since the company is paying for ad-share and can't support at least 1 current framework. Hope this helps!
