### ISSUE TITLE
Laravel 11 upgrade

### ISSUE THREAD

**Issue by Agathe-Brusset** [mailersend/mailersend-laravel-driver#46]

**Comment by Ticaga-Mike** [comment]
This is a must, I'm surprised it's not already been done.

**Comment by mrvnklm** [comment]
> This is a must, I'm surprised it's not already been done.

Indeed - I was looking for an alternative to mailgun for a new project and considered mailersend, but definetly reconsidering now...

**Comment by fosron** [comment]
We are escalating this and will have it done ASAP. Sorry for the inconvenience.
