### ISSUE TITLE
2.7.0 Breaks existing code

### ISSUE THREAD

**Issue by chrisgriff08** [mailersend/mailersend-laravel-driver#56]
You removed Variables in 2.7.0, this is a breaking change for all existing code, maybe you should consider making this a major release like 3.0 so it doesn't affect existing code if someone updates their libraries?

Also, is there any plan to deprecate Variables on the API side of things? Because that would cause all of my code to stop working if the API starts to not accept Variables.

**Comment by fosron** [comment]
Please contact info@mailersend.com for further support.
