### ISSUE TITLE
No way of using Advanced personalization with this package

### ISSUE THREAD

**Issue by koenhendriks** [mailersend/mailersend-laravel-driver#7]
I'm trying to use a foreach loop in my template with the advanced personalization but I can only set simple `substitutions` variables using the `Variable` builder class. 

Is it currently possible to use advanced personalization using this package? I can't seem to find any documentation, except the developer api docs for the general API.

[Api docs here.](https://developers.mailersend.com/api/v1/features.html#advanced-personalization)

**Comment by fosron** [comment]
Yes, at the moment only Simple personalization is supported. We will be adding support for Advanced personalization soon.

**Comment by koenhendriks** [comment]
Thanks for the quick response. I'm in need of this feature in a current project so i'll build my own request with Guzzle for now...
